-- 가입·재동의 때 받은 동의 이력. 덮어쓰지 않고 쌓는다.
-- 개인정보 수집·이용은 계약 이행 근거라 따로 동의받지 않고, 처리방침은 열람한 버전만 남긴다.
CREATE TABLE user_consents (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          varchar(255)             NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    terms_version    varchar(32)              NOT NULL,
    privacy_version  varchar(32)              NOT NULL,
    age_confirmed    boolean                  NOT NULL,
    marketing_opt_in boolean                  NOT NULL,
    consented_at     timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_consents_user_consented ON user_consents (user_id, consented_at DESC);
